# 日志配置文件

version: 1
disable_existing_loggers: false

# 格式化器
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  simple:
    format: "%(levelname)s - %(message)s"

# 处理器
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

# 记录器
loggers:
  core:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  v1:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  utils:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  paddleocr:
    level: WARNING
    handlers: [file]
    propagate: false

# 根记录器
root:
  level: INFO
  handlers: [console, file, error_file]
